### ISSUE TITLE
AssertionError in load_model_merged()

### ISSUE THREAD

**Issue by omg777** [zhangweichen2006/iCAN#3]
I have AssertionError when I run a2w_v2.py
Can help?
'''
pytorch 1.0.0.dev20181103
python3.5
'''
```
Traceback (most recent call last):
  File "a2w_v2.py", line 1003, in <module>
    main()
  File "a2w_v2.py", line 922, in main
    model_pretrained, diff = load_model_merged('resnet50', NUM_CLASS)
  File "a2w_v2.py", line 865, in load_model_merged
    diff = [s for s in diff_states(model.state_dict(), pretrained_state)]
  File "a2w_v2.py", line 865, in <listcomp>
    diff = [s for s in diff_states(model.state_dict(), pretrained_state)]
  File "a2w_v2.py", line 840, in diff_states
    assert len(not_in_1) == 0
AssertionError

```

**Comment by omg777** [comment]
@zhangweichen2006 
Thanks! I solved this with python2.7 and Pytorch0.4.

Can you upload the code for CAN not iCAN ?
iCAN is hard to understand for me..t.t

**Comment by zhangweichen2006** [comment]
The CAN's code is inside the iCAN's code. If you just want to run CAN, just simply comment all the Pseudo labeling part (from 213 to 330, except the initialization of Pseudo_set and dset['Pseudo']).

**Comment by omg777** [comment]
@zhangweichen2006 
Now I can run CAN. thanks.

Anyway, there are 4 weight variables (w_l1, w_l2, w_l3, w_main) in the code. 
(I think w_main is for the last weight of last layer.)
Why only four weight variables are used even if 'resnet50' is used?

**Comment by zhangweichen2006** [comment]
@omg777 Number of weights is a hyper-parameter, the first layer(block) is not used in this code. You can have a try to add a weight and a domain discriminator for ResNet50 layer 1.

**Comment by omg777** [comment]
@zhangweichen2006 
Thanks for reply! 
I have some questions.. sorry to bother you.

[1] I missunderstand that number of discriminator is always m. but you mean that number of discriminator is a hyper-parameter. If I select 4 discriminator, then the position is also hyper-parameters?
[2] What is the l1_rev, l2_rev and l3_rev ?
[3] What's the role of ResNet50 ? 
    Is it right that you uses pre-trained ResNet50 as Encoder in iCAN, then fine-tuning the encoder with discriminator and classifier ?

**Comment by zhangweichen2006** [comment]
@omg777
[1] Yes the positions are also hyper-parameters, but in this work, it is tried to add the discriminator after the pooling layer when the receptive field change.
[2] l1_rev, l2_rev and l3_rev are just to pass the sign of lambdas(to use reverse gradient or not) to Gradient Reversal Layer or main training function.
[3] ImageNet pre-trained ResNet50 plays as a backbone feature extractor. 

Actually, we can discuss these problems in emails, you can see it on my GitHub site.
