### ISSUE TITLE
AttributeError: module 'torch' has no attribute 'as_tensor'

### ISSUE THREAD

**Issue by kinredon** [zhangweichen2006/iCAN#7]
I use pytorch 0.4.0 to run `a2w_v2.py` and it occurs the following error:
 
`
Replacing the following state from initialized resnet50 : ['fc.weight', 'fc.bias']
=> no checkpoint model
Traceback (most recent call last):
  File "/youedata/dengjinhong/github/iCAN/a2w.py", line 1001, in <module>
    main()
  File "/youedata/dengjinhong/github/iCAN/a2w.py", line 998, in main
    model = train_model(model_dann, optimizer_ft, optimizer_pseudo, exp_lr_scheduler, pseudo_lr_scheduler, num_epochs=total_epochs, start_epoch=start_epoch, best_acc=best_prec, loaded_model = loadmodel, draw_dict=draw_dict)
  File "/youedata/dengjinhong/github/iCAN/a2w.py", line 130, in train_model
    target_dict = [(i,j) for (i,j) in dset_loaders['target']]
  File "/youedata/dengjinhong/github/iCAN/a2w.py", line 130, in <listcomp>
    target_dict = [(i,j) for (i,j) in dset_loaders['target']]
  File "/youedata/dengjinhong/anaconda3/envs/pytorch0.4.0/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 264, in __next__
    batch = self.collate_fn([self.dataset[i] for i in indices])
  File "/youedata/dengjinhong/anaconda3/envs/pytorch0.4.0/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 264, in <listcomp>
    batch = self.collate_fn([self.dataset[i] for i in indices])
  File "/youedata/dengjinhong/anaconda3/envs/pytorch0.4.0/lib/python3.6/site-packages/torchvision-0.2.3a0+8759f30-py3.6.egg/torchvision/datasets/folder.py", line 132, in __getitem__
  File "/youedata/dengjinhong/anaconda3/envs/pytorch0.4.0/lib/python3.6/site-packages/torchvision-0.2.3a0+8759f30-py3.6.egg/torchvision/transforms/transforms.py", line 60, in __call__
  File "/youedata/dengjinhong/anaconda3/envs/pytorch0.4.0/lib/python3.6/site-packages/torchvision-0.2.3a0+8759f30-py3.6.egg/torchvision/transforms/transforms.py", line 163, in __call__
  File "/youedata/dengjinhong/anaconda3/envs/pytorch0.4.0/lib/python3.6/site-packages/torchvision-0.2.3a0+8759f30-py3.6.egg/torchvision/transforms/functional.py", line 206, in normalize
AttributeError: module 'torch' has no attribute 'as_tensor'
`
How can I fix it? 
Thanks.

**Comment by zhangweichen2006** [comment]
Hi Kinredon,

I think that is the problem of Pytorch or python version mismatch. I was using python2.7 to run the code. Seems the error is about the torch tensor conversion for the input images. Would you mind to install the python2.7 version, or trying to print more debugging errors? 

Cheers.

**Comment by zhangweichen2006** [comment]
By the way, I believe seems it is more likely the problem of different version of torchvision. Please try to pip or conda install torchvision 0.2.2 or trying versions around 0.2.0 first.

**Comment by kinredon** [comment]
Thank for your response.
My python version is 3.6.8 and I will check the version of  torchvision.

**Comment by kinredon** [comment]
Thank for your suggestions again!
I changed torchvision version to 0.2.1 which enable to the code run correctly.
